name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Using LTS version

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./ui

      - name: Run linters
        run: npm run lint
        working-directory: ./ui

      - name: Run Prettier check
        run: npx prettier --check "ui/**/*.{ts,tsx,js,jsx,json,md,yml}" # Generic check, can be refined

      - name: Run tests
        run: npm test
        working-directory: ./ui
